### PR TITLE
INIT Debug Branch

### PR DESCRIPTION
**Pull request by markkhoo**
@Lckythr33 and I removed 4 packages to get through the metro build step (the app doesn't work in this state of course). The following packages the were removed need to be resolved:
1.  `@t2tx/react-native-universal-pedometer`
2.  `react-native-local-resource`
3.  `react-native-localization`
4.  `react-native-reanimated`

### CODE REVIEW

**Comment by francisli** [comment]
@markkhoo I've gotten this branch to the point where I can at least see the splash screen, by commenting out references to the libraries not included.

Note that I was able to re-add the latest version of react-native-localization, not sure why you had to remove that package...?

**Comment by francisli** [comment]
Need to find an alternative implementation to loading text files that doesn't use react-native-local-resource

**Comment by francisli** [comment]
I also see warnings/errors related to the newer version of react-navigation

**Comment by francisli** [comment]
@markkhoo if this code builds and launches for you on Android and you can see the splash screen, I think we should merge it into main and then create a bunch of issues for all the individual things we need to fix, such that multiple team members can help work on things.

**Comment by markkhoo** [comment]
I was able to get the app to the splash screen. Should we merge the branch in?

**Comment by francisli** [comment]
@markkhoo great, I'm going to merge in now.

**Comment by francisli** [comment]
@markkhoo let's start populating the Issues list with everything that we know we need to do based on where we're at right now.

**Pull request merged**
